blueprint:
  name: Notification
  description: >-
    A script that sends an notification to two devices
  domain: script
  source_url: https://github.com/adiko01/HomeAssistant-Blueprints/blob/master/notification/notification-for-2-devices.yaml
  input:
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
    notify_device2:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
    title:
      name: "Title"
      description: "The title of the button shown in the notification."
      default: ""
      selector:
        text:
    message:
      name: "Message"
      description: "The message body"
      selector:
        text:

mode: restart

sequence:
  - alias: "Send notification"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    title: !input title
    message: !input message
  - alias: "Send 2nd notification"
    domain: mobile_app
    type: notify
    device_id: !input notify_device2
    title: !input title
    message: !input message

